version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ferrtech-php
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: ferrtech-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ferr-Tech!120310  # Root password only
      MYSQL_DATABASE: testrun_6             # Initial DB to create
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
